#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Media {
                namespace Animation {
                    ref class Storyboard;
                }
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Frame;
                ref class Grid;
                ref class Image;
                ref class TextBox;
                ref class StackPanel;
                ref class Button;
                ref class Slider;
                ref class AppBarToggleButton;
            }
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                namespace Primitives {
                    ref class Popup;
                }
            }
        }
    }
}

namespace IotTemperatureWatcher
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class Config : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Media::Animation::Storyboard^ RackAnimationStoryboard;
        private: ::Windows::UI::Xaml::Controls::Frame^ FrameConfig;
        private: ::Windows::UI::Xaml::Controls::Grid^ GridConfig;
        private: ::Windows::UI::Xaml::Controls::Image^ serverRackOpened;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBoxUpperFan1;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBoxUpperFan2;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBoxSTL;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBoxSTR;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBoxSCL;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBoxSCR;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBoxSBL;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBoxSBR;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBoxErrors;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBoxInfo;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBoxThresholdUpperSensor;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBoxThresholdCenterSensor;
        private: ::Windows::UI::Xaml::Controls::TextBox^ textBoxThresholdLowerSensor;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ buttonFanConfigPanel;
        private: ::Windows::UI::Xaml::Controls::Button^ buttonAddFan;
        private: ::Windows::UI::Xaml::Controls::Button^ buttonRemoveFan;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ buttonSenConfigPanel1;
        private: ::Windows::UI::Xaml::Controls::Button^ buttonAddSensor;
        private: ::Windows::UI::Xaml::Controls::Button^ buttonRemoveSensor;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ buttonSenConfigPanel2;
        private: ::Windows::UI::Xaml::Controls::Button^ buttonChangeThresholds;
        private: ::Windows::UI::Xaml::Controls::Primitives::Popup^ popupConfig;
        private: ::Windows::UI::Xaml::Controls::Slider^ sliderThresholdLowerText;
        private: ::Windows::UI::Xaml::Controls::Slider^ sliderThresholdUpperText;
        private: ::Windows::UI::Xaml::Controls::Button^ buttonPopupConfigSave;
        private: ::Windows::UI::Xaml::Controls::AppBarToggleButton^ appBarToggleButtonFanConfig;
        private: ::Windows::UI::Xaml::Controls::AppBarToggleButton^ appBarToggleButtonSensorConfig;
        private: ::Windows::UI::Xaml::Controls::AppBarToggleButton^ appBarToggleButtonThresholdConfig;
    };
}

