//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::IotTemperatureWatcher::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::IotTemperatureWatcher::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->textBlockVentilator1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 2:
            {
                this->textBlockVentilator2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 3:
            {
                this->textBlockTemperature1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 4:
            {
                this->textBlockTemperature2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 5:
            {
                this->toggleSwitchCustomMode = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->toggleSwitchCustomMode))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::toggledToggleSwitchCustomMode);
            }
            break;
        case 6:
            {
                this->toggleSwitchVentilator1 = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->toggleSwitchVentilator1))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::toggledToggleSwitchVentilator1);
            }
            break;
        case 7:
            {
                this->toggleSwitchVentilator2 = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->toggleSwitchVentilator2))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::toggledToggleSwitchVentilator2);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::IotTemperatureWatcher::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


