//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::IotTemperatureWatcher::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::IotTemperatureWatcher::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                this->checkBoxAdvancedCustomMode = safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->checkBoxAdvancedCustomMode))->Checked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::checkedCheckBoxAdvancedCustomMode);
                (safe_cast<::Windows::UI::Xaml::Controls::CheckBox^>(this->checkBoxAdvancedCustomMode))->Unchecked += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::uncheckedCheckBoxAdvancedCustomMode);
            }
            break;
        case 2:
            {
                this->textBlockVentilator1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 3:
            {
                this->textBlockVentilator2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 4:
            {
                this->textBlockTemperature1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 5:
            {
                this->textBlockTemperatureText1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 6:
            {
                this->textBlockTemperatureText2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 7:
            {
                this->textBlockTemperature2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 8:
            {
                this->textBlockUpperTemp1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 9:
            {
                this->textBlockUpperTemp1V2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 10:
            {
                this->textBlockLowerTemp1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 11:
            {
                this->textBlockUpperTemp2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 12:
            {
                this->textBlockUpperTemp2V1 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 13:
            {
                this->textBlockLowerTemp2 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 14:
            {
                this->toggleSwitchCustomMode = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->toggleSwitchCustomMode))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::toggledToggleSwitchCustomMode);
            }
            break;
        case 15:
            {
                this->toggleSwitchVentilator1 = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->toggleSwitchVentilator1))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::toggledToggleSwitchVentilator1);
            }
            break;
        case 16:
            {
                this->toggleSwitchVentilator2 = safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::ToggleSwitch^>(this->toggleSwitchVentilator2))->Toggled += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::toggledToggleSwitchVentilator2);
            }
            break;
        case 17:
            {
                this->sliderUpperTemp1 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sliderUpperTemp1))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&MainPage::valueChangedSliderUpperTemp1);
            }
            break;
        case 18:
            {
                this->sliderUpperTemp1V2 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sliderUpperTemp1V2))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&MainPage::valueChangedSliderUpperTemp1V2);
            }
            break;
        case 19:
            {
                this->sliderLowerTemp1 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sliderLowerTemp1))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&MainPage::valueChangedSliderLowerTemp1);
            }
            break;
        case 20:
            {
                this->sliderUpperTemp2 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sliderUpperTemp2))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&MainPage::valueChangedSliderUpperTemp2);
            }
            break;
        case 21:
            {
                this->sliderUpperTemp2V1 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sliderUpperTemp2V1))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&MainPage::valueChangedSliderUpperTemp2V1);
            }
            break;
        case 22:
            {
                this->sliderLowerTemp2 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->sliderLowerTemp2))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&MainPage::valueChangedSliderLowerTemp2);
            }
            break;
        case 23:
            {
                this->progressBar2 = safe_cast<::Windows::UI::Xaml::Controls::ProgressBar^>(__target);
            }
            break;
        case 24:
            {
                this->progressBar1 = safe_cast<::Windows::UI::Xaml::Controls::ProgressBar^>(__target);
            }
            break;
        case 25:
            {
                this->popupTest = safe_cast<::Windows::UI::Xaml::Controls::Primitives::Popup^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Popup^>(this->popupTest))->Opened += ref new ::Windows::Foundation::EventHandler<::Platform::Object^>(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Platform::Object^))&MainPage::openedPopupTest);
                (safe_cast<::Windows::UI::Xaml::Controls::Primitives::Popup^>(this->popupTest))->Closed += ref new ::Windows::Foundation::EventHandler<::Platform::Object^>(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Platform::Object^))&MainPage::closedPopupTest);
            }
            break;
        case 26:
            {
                this->textBlockPopupErrorMessage = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 27:
            {
                this->buttonPopupOk = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->buttonPopupOk))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::IotTemperatureWatcher::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::clickedButtonPopupOk);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::IotTemperatureWatcher::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


